#!/usr/bin/env zsh

function nztunnel() {

	typeset -a hostname
	typeset -a mode
	typeset -a port
	typeset -a ip

	help() {
		echo 'Usage: nztunnel <hostname> <mode>'
		echo '\033[1;34;1mhostname: connect server hostname.\033[0m'
		echo '\033[1;34;1mmode: start|stop\033[0m'
	}
	
	connect() {
		ssh -N -f -L $port:$ip:22 {jump server user}@{jump server hostname} -p 22
		echo "\033[1;32;1m[connect]\033[0m ip:$ip"
		echo "\033[32;4m[portForward]\033[0m localhost:$port"
	}

	disconnect() {
		ps ax | grep ssh | grep $port | awk '{ print "kill -9", $1 }' | sh
		echo "\033[1;31;1m[disconnect]\033[0m ip:$ip"
	}

	switch() {
		case $hostname in
			sample)
				port={any port}
				ip={connect server}
				;;
			*)
				echo 'unknown hostname.'
				exit
		esac
	}

	if (( $# < 2 )); then
		help
		return
	fi

	hostname=$1
	mode=$2
	switch

	case $mode in
		connect)
			connect
			;;
		disconnect)
			disconnect
			;;
		*)
			echo 'usage: nztunnel [hostname] [connect|disconnect]'
			;;
	esac

}

nztunnel $@
